### ISSUE TITLE
Result is "unpredictable" if library_file contains more sequences

### ISSUE THREAD

**Issue by ondra-m** [wrpearson/fasta36#21]
I'm comparing query_file (with one sequence) against library_file (with more sequences).

Version `36.3.8h Aug, 2019`

1. If library_file contains more than 500 records, the program just show "0 hits found". Can you make a text more informative or allow more records?
2. Some records from library_file are missing in the result.

([files from the exampels](https://github.com/wrpearson/fasta36/files/4337382/sequences.zip))

`ssearch36 -3 -m 8CC mer31.fa library.fa`
- show 46 hits
- but file contains 54 records
- for example a sequence ">53" from library.fa is missing

`ssearch36 -3 -m 8CC mer31.fa 53.fa`
- if I scan query against only ">53" its working

Am I doing something wrong?
Thanks

**Comment by wrpearson** [comment]
The reason you are not seeing a result with >53 when you use the -3 option (only compare in the forward direction) is because the E()-value for that alignment is > 10 (the default threshold for displaying results).  To see all the results, use the option "-E 100000".

I do not understand the problem with 0 hits found -- this is also an E()-value threshold phenomenon (there are no hits below the E()-value).  The -m 8CC format is constrained by what BLAST shows in its tabular format.   More information is available with other output formats.

Bill Pearson


Begin forwarded message:

**Comment by ondra-m** [comment]
Thank you very much
