### ISSUE TITLE
glsearch36 and similarity

### ISSUE THREAD

**Issue by RamilNurtdinov** [wrpearson/fasta36#23]
Hi

I am making glsearch36 of my protein sequences against protein database.
I need BLAST tabular format "-m 8C". now it puts %identity there.
Independently on presence or absence "-DSHOWSIM" option in Makefile.

For distant proteins %similarity is much better.
Probably you agree with me, that reporting 19.4% identity is not the same as reporting 54% similarity for the same alignment.
Is it possible to report also similarity?

**Comment by wrpearson** [comment]
It would not be difficult; the issue is how to tell -m 8CBl that an additional field (similarity) is desired.

I can imagine adding a -m 8CBls option, where 's' is for similarity.

Better (but much more time consuming) would be to add the option that BLAST provides to specify the fields.

I will look into it.

Bill Pearson

Begin forwarded message:

**Comment by RamilNurtdinov** [comment]
Hi Bill 
"-m 8CBls" to put similarity instead of identity or aside is perfect solution.
I myself is able to edit you code and make replacement. However it will be impossible to distribute our pipeline with you program without this correction "-m 8CBls".

**Comment by wrpearson** [comment]
It is a relatively simple change, but I think it would be better not to require the ‘l’ before the ‘s’, and to also allow ‘sl’ as well as ‘ls’, so it will take a few weeks, but it should happen relatively soon.

Bill

On May 15, 2020, at 4:41 PM, RamilNurtdinov <notifications@github.com> wrote:

﻿

Hi Bill
"-m 8CBls" to put similarity instead of identity or aside is perfect solution.
I myself is able to edit you code and make replacement. However it will be impossible to distribute our pipeline with you program without this correction "-m 8CBls".

**Comment by wrpearson** [comment]
An updated version of fasta36 on branch v36.3.8 is available that provides the -m8CBls option (or -m8CBs) to include percent similarity as well as percent identity.

Bill Pearson

**Comment by RamilNurtdinov** [comment]
Hi Bill

I searched for default values for gap-open and gap-extend options in glsearch36 aligning protein sequences.
I found some text in "initfa.c". 
LNW_PID, "GLSEARCH", "lnw", "GLSEARCH performs a global-query/local-library search", NULL, 404, "BL50", -2, 0, 0, 0, 10.0, 0, 0.0, 1}
I found also
  {'f', 1, "gapopen", "gap-open penalty", NULL, 0, 0, 0, 0, 0.0, 0.0, NULL},
  {'g', 1, "gapext", "gap-extension penalty", NULL, 0, 0, 0, 0, 0.0, 0.0, NULL},

-----
It is difficult to conclude what exact values are default.

Can you please clarify this?

**Comment by wrpearson** [comment]
The default gap penalties are set by the scoring matrix selection code, which is found in apam.c (standard_pam()) and uses the values in spam.h.  (I'm not sure what the code you found does these days -- the table based approach allows the scoring matrix to drive the gap selection).

This bit of code from initfa.c does the work:

  /* initialize a pam matrix */
  SAFE_STRNCPY(ppst->pamfile,pgm_def.smstr,MAX_FN);
  standard_pam(ppst->pamfile,ppst,del_set,gap_set);
  ppst->have_pam2 = 0;

If del_set or gap_set are  zero, then ppst->gap_val and ->del_val are set from the upam.h std_pams[] table.

Bill

Begin forwarded message:

**Comment by RamilNurtdinov** [comment]
Many thanks for your help.
