### ISSUE TITLE
Compile fasta36 binaries as shared libraries instead

### ISSUE THREAD

**Issue by jjtapia** [wrpearson/fasta36#27]
I currently have a program that makes programmatic use of some utilities in the fasta36 suite, repeatedly and up to a thousands of times per execution. The input sequences to the tools are obtained sequentially so there is no way around having to call it multiple times. Although each individual execution does not take much time, Constantly calling the tools is currently the biggest bottleneck in my pipeline, so I was wondering if it'd be possible to compile the tools as libraries instead of executables as a way to address the problem. I was trying to look into the Makefiles themselves and I *think* `Makefile.pcom_t` is the makefile that would need to be modified to add library compilation flags. What would be your take on it?

**Comment by wrpearson** [comment]
I do not believe that any of the fasta Makefiles that specifies linking to shared or static libraries.    As far as I know, by default executables are linked against shared libraries.  In any case, I do not think Makefile.pcom_t has much to do with shared/static library selection.

**Comment by wrpearson** [comment]
I'm sorry that I misunderstood your request.

I'm afraid I do not know much about building shared libraries, and an unfortunate design decision made 20+ years ago probably makes this much more difficult.  The design decision was to give functions that do the same thing (but with different types of sequences, e.g. DNA vs protein) the same name.  So there is a set of functions: init_work(), do_work(), do_opt() that have the same name but implement different algorithms.  To make a library, one would need to separate the different names into different functions.

If you told me more about the kinds of calculations you are doing, I could probably make a more useful suggestion.

Bill Pearson

**Comment by jjtapia** [comment]
Hello,

What I'm trying to do is to have an arbitrary Python script run an utility in fasta36 (ssearch36 in my instance). Currently, to do this process I  have to create a file with the input sequence (I/O cost), run the executable (so switch contexts from my script). have the script read in the sequence (more I/O), execute the fasta36 function and reading back the result (this one is not too bad since the console output can just be piped in into the calling script). Once I do this operation thousands of times the execution time starts pilling up.

Ideally I'd like to be able to run as a library so that I can just pipe in the input sequence as a string to the fasta36 utility, rather than having to go write the sequence into a file only to have the tool read it back in. This would streamline execution costs quite a bit I believe. Based on what you tell me there may not be a good way to do this though.

As an alternative since ssearch36 is essentially performing Smith-waterman based local alignment I've been trying to use alternative smith-waterman libraries like [parasail](https://github.com/jeffdaily/parasail-python), however I have been having issues lining up the results between the two tools (ssearch36 and parasail). I can make a separate github issue detailing the problem.

**Comment by wrpearson** [comment]
It would help me to have a few more specifics, but FASTA does not need to have a file to read (at least as the query) -- it can read the query from stdin using the "@" filename. If all you  want is to be able to pipe a sequence to fasta/ssearch36 and capture the output, you can do this without a library (or a query file).

Unfortunately, at the moment it cannot read both the query and subject sequences from stdin, but I can certainly see how that would be useful in some of my own work, so I should implement it.

But perhaps the function you need already exists.

Bill Pearson

Begin forwarded message:


From: Jose Juan Tapia ***@***.******@***.***>>

Subject: Re: [wrpearson/fasta36] Compile fasta36 binaries as shared libraries instead (#27)

Date: May 20, 2021 at 3:50:43 PM MDT

To: wrpearson/fasta36 ***@***.******@***.***>>

Cc: William Pearson ***@***.******@***.***>>,  Comment ***@***.******@***.***>>

Reply-To: wrpearson/fasta36 ***@***.******@***.***>>


Hello,

What I'm trying to do is to have an arbitrary Python script run an utility in fasta36 (ssearch36 in my instance). Currently, to do this process I have to create a file with the input sequence (I/O cost), run the executable (so switch contexts from my script). have the script read in the sequence (more I/O), execute the fasta36 function and reading back the result (this one is not too bad since the console output can just be piped in into the calling script). Once I do this operation thousands of times the execution time starts pilling up.

Ideally I'd like to be able to run as a library so that I can just pipe in the input sequence as a string to the fasta36 utility, rather than having to go write the sequence into a file only to have the tool read it back in. This would streamline execution costs quite a bit I believe. Based on what you tell me there may not be a good way to do this though.

**Comment by jjtapia** [comment]
I see. I did not know ssearch36 could read the query from stdin. That could indeed address a large part of my issue without much rework. I will try that out. Thank you for the suggestion
