### ISSUE TITLE
map_db and .xin files

### ISSUE THREAD

**Issue by gundizalv** [wrpearson/fasta36#43]
Hi
I've been looking for a more detailed explanation of how map_db works and how to use properly the resulting .xin files. I cannot use .xin instead of .fa libraries. My question is, during a search, both .fa and .xin work together? The manual is not very clear for me about this issue

**Comment by wrpearson** [comment]
If you have a fasta format library called my_file.fa (or .lseg or .lib or anything else), and there is a second file with the same name with an additional .xin suffix (e.g. my_file.fa.xin), the fasta programs can read the my_file.fa file more efficiently. You do not want to use the .xin file in the command line, but if it exists and matches the .fa file in size, it will be used.

Bill Pearson

On May 20, 2022, at 1:19 PM, gundizalv ***@***.***> wrote:

﻿

I've been looking for a more detailed explanation of how map_db works and how to use properly the resulting .xin files. I cannot use .xin instead of .fa libraries. My question is, during a search, both .fa and .xin work together? The manual is not very clear for me about this issue

**Comment by gundizalv** [comment]
Oh, it's very clear for me now. 
Thanks!
