### ISSUE TITLE
Why is FASTA called FASTA?

### ISSUE THREAD

**Issue by Maithy15** [wrpearson/fasta36#45]
Hi,

I know FAST-All is shortened to FASTA, but why is it called FAST? Is FAST an acronym, or is it just an adjective?

The 1985 paper has a note that says

"The algorithm used to calculate the optimized alignment is considerably faster than the normal Needleman-Wunsch procedure, because it only compares the two sequences along a narrow band centered on the initial alignment. With this restriction, gaps may be inserted in either sequence so as to include areas of similarity up to 16 residues from the offset of the initial alignment. Some proteins will not be completely aligned with this limited local optimization because the method focuses on the most similar region; nevertheless, scores of related proteins increase substantially."

If FAST is just an adjective, could you tell me who came up with it?

Thanks
Maithy

**Comment by wrpearson** [comment]
Just an adjective.  The first paper using the approach described FASTP - for fast protein comparison.  Then there was FASTN (nucleotide), but no paper. FASTA put them together, and works with other alphabets.

Bill Pearson

On Oct 7, 2022, at 4:49 PM, Maithy15 ***@***.***> wrote:

﻿

Hi,

I know FAST-All is shortened to FASTA, but why is it called FAST? Is FAST an acronym, or is it just an adjective?

The 1985 paper has a note that says

"The algorithm used to calculate the optimized alignment is considerably faster than the normal Needleman-Wunsch procedure, because it only compares the two sequences along a narrow band centered on the initial alignment. With this restriction, gaps may be inserted in either sequence so as to include areas of similarity up to 16 residues from the offset of the initial alignment. Some proteins will not be completely aligned with this limited local optimization because the method focuses on the most similar region; nevertheless, scores of related proteins increase substantially."

If FAST is just an adjective, could you tell me who came up with it?

Thanks
Maithy
