### ISSUE TITLE
remark regarding the output provided when using option -m 9

### ISSUE THREAD

**Issue by peutch** [wrpearson/fasta36#51]
Hi,

It seems to me that there are two columns (the one before 'bits' and the one after '%_sim') that always provide the same values but with different column names:
- first labeled 'ls-w'  and second 'lsw' in lalign36,
- first labeled 's-w' and second 'sw' in ssearch36,
- first labeled 'opt' and second 'sw' in fasta36.
(I did not look at the other tools).
Is that the case that they are «redundant»?
Always? Or is this may depend some other options?

Thanks,
Patrice

**Comment by wrpearson** [comment]
The values are slightly different, which is why they have slightly different abbreviations. 's-w', 'ls-w', and 'opt' are scores that are used for the statistics calculation. 'sw' and 'lsw' are the final alignment scores, which may be different from the scores used in the statistics calculation.  For example, by fasta36 uses 'opt' to calculate statistical significance, but produces a final 'sw' (Smith-Waterman) alignment score.
