### ISSUE TITLE
wishes or remarks about LALIGN

### ISSUE THREAD

**Issue by peutch** [wrpearson/fasta36#55]
Hi,

LALIGN says `The best alignments are:` while the others (all?) say `The best scores are:`.
Making it consistent could simplify a generic output parser.

Moreover it seems to me that LALIGN has a default expectation value cutoff (E() < 1) and
not (E() < 10), no?

But regarding this two points, the documentation says (p.30 in the PDF of May 31, 2023):

**The search seemed to work, but I do not see any results.** – In command line mode (the
default), all the FASTA programs limit the number of high scoring sequences shown using an ex-
pectation value cutoff (E() < 10 for proteins; E() < 2 for DNA). Sometimes, a search will complete
successfully (you see the message `XXXX residues in YYY sequences`) but the message: `!! No
sequences with E() < 10` instead of `The best scores are:. `

But maybe I missed some special features regarding LALIGN reading it.

Many thanks for all,
Patrice

**Comment by wrpearson** [comment]
LALIGN is not a search program, so some of its labeling is different and the E()-value thresholds are a bit more subtle.

In particular, it is not clear what the appropriate E()-value threshold is for LALIGN, because it has not done a search.  For the search programs, the E()-value is calculated from the p()-value of the alignment score times the size of the database searched.  But with LALIGN, there is no database.  So should the database size be 1?  I'm uncomfortable with that assumption, because it means that scores that would not be even close to significant in a database search suddenly get very significant values.  However, since it has no other information, LALIGN assumes a database size of 1 when calculating E()-values.  This is a very very generous assumption, which is why the default cutoff is E()<1.

Bill Pearson

Begin forwarded message:


From: Patrice Duroux ***@***.******@***.***>>

Subject: [wrpearson/fasta36] wishes or remarks about LALIGN (Issue #55)

Date: June 23, 2023 at 8:54:56 AM MDT

To: wrpearson/fasta36 ***@***.******@***.***>>

Cc: Subscribed ***@***.******@***.***>>

Reply-To: wrpearson/fasta36 ***@***.******@***.***>>


Hi,

LALIGN says The best alignments are: while the others (all?) say The best scores are:.
Making it consistent could simplify a generic output parser.

Moreover it seems to me that LALIGN has a default expectation value cutoff (E() < 1) and
not (E() < 10), no?

But regarding this two points, the documentation says (p.30 in the PDF of May 31, 2023):

The search seemed to work, but I do not see any results. – In command line mode (the
default), all the FASTA programs limit the number of high scoring sequences shown using an ex-
pectation value cutoff (E() < 10 for proteins; E() < 2 for DNA). Sometimes, a search will complete
successfully (you see the message XXXX residues in YYY sequences) but the message: !! No sequences with E() < 10 instead of The best scores are:.

But maybe I missed some special features regarding LALIGN reading it.

Many thanks for all,
Patrice

**Comment by peutch** [comment]
Hi,

Oh, I totally forgot about this.
So no way to have something that combines easily a search and gives also multiple matches if any in only one run (like the BLAST HSPs), if I understand correctly.

Thanks again,
Patrice

**Comment by wrpearson** [comment]
No, that is incorrect.  If fasta36 finds multiple non-overlapping alignments from the perspective of the query sequence and library sequence, (e.g. HSPs), it will report them (focussing on the longest possible alignments).

This is what BLAST does as well.  (For example, you can blast2 sequences P0DP23<https://www.uniprot.org/uniprotkb/P0DP23/entry> and P62157 at the NCBI, and you will only get one alignment.)

For this case (human vs bovin calmodulin), lalign will show three alignments that are not the end-to-end alignment.  These are not shown by fasta36 or blast because the first alignment (end-to-end) covers all the residues in the lower scoring non-overlapping local alignments.
