### ISSUE TITLE
Desite glsearch with protein queries vs genomic DNA library

### ISSUE THREAD

**Issue by tseemann** [wrpearson/fasta36#6]
Bill,

I am the author of Prokka a bacterial genome annotation tool. Currently it just finds coding-regions de novo using Prodigal, and then assigns function by best BLASTP hit against a protein database.

What I would prefer to do is take a set of trusted intact proteins and glocally align them to the genome, and report back *non overlapping* hits.  Like "tiling" the genome with all the best protein hits that *fully* align.  It should handle frame-shifts too (homopolymer genome errors are common). It should also not penalize alignments that hit the ends of contigs (long end gaps).

I am a big fan of `glsearch` but it only works DNA:DNA or AA:AA.   `lalign` might be the right tool, but It only does local alignment. The new BLAST `-culling_limit` helps prevents overlapping hits, but still only local alignment.
I think in the past TIGR used BLAST to find putative hits, then used glocal alignment to pin down the details, but I would prefer a more generic solution.

Do you have any suggestions on how to tackle this problem?

Torsten

**Comment by wrpearson** [comment]
Torsten --

I think there is already a solution to your alignment problem built into tfastx/y36 (and earlier versions).  We actually implemented this many years ago when working on the Salmonella genome annotation.

If you use the option "-t t" with any of the FASTA programs (but particularly tfastx36), the program automatically adds a '*' to the end of the query protein sequence, and scores a ** at the end of the alignment if there is an alignment with a termination codon.  This allows you to very quickly determine whether there is a full-length match.  I am working on a similar problem finding Xenopus tropicalis ORFs (the genome is not well assembled or annotated), so I compare human proteins against an X. tropicalis RNA-seq assembly looking for full-length matches.

I think that using the "-t t" option with tfastx36 (or perhaps even tfasty36) would get you very close to what you want.  You would still have to do some post-processing to join proteins that span contigs.

With the FASTA programs (which originally only provided one alignment per query/subject sequence, a problem with long contigs), you have two options for finding multiple homologs in the same contig: (1) just run the program, probably with a low E()-value cut-off, and require an equally low E()-value cutoff for any secondary alignment (-E "1e-10 1e-10"); (2) use the "-N ####" option to segment your contigs in to ####-long overlapping fragments (this used to be the only option).  You might try both and see which does a better job of avoiding the problems you are having with BLASTP.

Please note that by using the -mBB option (or -m 8CB, my favorite), it is possible to get BLAST-like output that should fit into the rest of your analysis pipeline.

If you really think it would be better to have a tglsearch-like program (global in query, local in subject), it would not be hard to make tfastx36 do this (tfasty36 might be harder, because the code is more complex and I do not understand it as well -- someone else developed it).  But I don't think you want to force things to be global.  I think it would be better for the local aligner to generate a global alignment, with the termination codon.

Bill Pearson

Begin forwarded message:

**Comment by wrpearson** [comment]
Let me suggest an alternative -- perhaps assigning a very high positive score for 'M:M' alignment, or, alternatively, making a special character for the initial-Met (e.g. J) and assigning a very high score for a "J:M" match.  This would address the example you posed.

Bill Pearson

Begin forwarded message:

**Comment by tseemann** [comment]
Using a special character for the start amino acid in my protein database is an intriguing hack!

I will definitely look into this idea - thank you for your thoughts on this issue.
