### ISSUE TITLE
Identity differs with different options

### ISSUE THREAD

**Issue by yzhang-github-pub** [wrpearson/fasta36#62]
In identity calculation, -m8 seems to have indels excluded, while -m9 has indels in the calculation

**Comment by wrpearson** [comment]
Yes, this is correct, and it is true both for identity and similarity.

-m 8 uses the BLAST method of calculating identity (because it is copying a blast output format), and BLAST does not include identities in the denominator of the identity calculation.

-m 9 uses the FASTA method, which does include indels.

I think that the BLAST calculation is more reasonable, but for historical consistency, I keep the FASTA calculation.  If you always want the BLAST calculation (even in -m 9), then you can use the -XB option.

Bill Pearson

Begin forwarded message:


From: yzhang-github-pub ***@***.******@***.***>>

Subject: [wrpearson/fasta36] Identity differs with different options (Issue #62)

Date: June 4, 2024 at 8:36:06 AM MDT

To: wrpearson/fasta36 ***@***.******@***.***>>

Cc: Subscribed ***@***.******@***.***>>

Reply-To: wrpearson/fasta36 ***@***.******@***.***>>


In identity calculation, -m8 seems to have indels excluded, while -m9 has indels in the calculation
