### ISSUE TITLE
Build fails with LTO due to type mismatch

### ISSUE THREAD

**Issue by eli-schwartz** [wrpearson/fasta36#63]
I tried to build with the following {C,CXX,FC,LD}FLAGS to optimize the build: `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

Link-Time Optimization is a massively global compiler optimization pass which is pretty handy for producing faster executables. It also has the interesting property that because the compiler does whole-program analysis using bytecode, it can save type information and perform error checks that it normally doesn’t have enough insight for. In particular, checking for ODR issues and checking function type signature mismatches.

Note that *all* the -Werror=* flags are used to help detect cases where the compiler tries to optimize by assuming UB cannot exist in the source code -- if it does exist, ordinarily the code would be miscompiled, and this says to make the miscompilation a fatal error.

I got this error:
```
make: Entering directory '/var/tmp/portage/sci-biology/fasta-36.3.8i/work/fasta36-36.3.8i_14-Nov-2020/src'
x86_64-pc-linux-gnu-gcc -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -msse2 -ffast-math -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0 -o ../bin/glsearch36 comp_mthr9.o	 work_thr2.o  pthr_subs2.o compacc2_t.o   showbest.o build_ares.o re_getlib.o mshowalign2_t.o htime.o apam.o doinit.o init_lnw_sse.o droplnw_sse.o glocal_sse2.o gwm_align.o calcons_sw.o scale_sn.o karlin.o  lgetlib.o lgetaa_m.o c_dispn.o ncbl2_mlib.o lib_sel.o url_subs.o mrandom.o pssm_asn_subs.o -lm   -lpthread
compacc2e.c:959:1: error: type of ‘re_openlib’ does not match original declaration [-Werror=lto-type-mismatch]
  959 | re_openlib(struct lmf_str *, int outtty);
      | ^
nmgetlib.c:514:3: note: type mismatch in parameter 2
  514 |   re_openlib(struct lmf_str *om_fptr, struct lib_struct *lib_p, int outtty)
      |   ^
nmgetlib.c:514:3: note: ‘re_openlib’ was previously declared here
nmgetlib.c:514:3: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
mshowbest.c:62:1: error: type of ‘s_annot_to_aa1a’ does not match original declaration [-Werror=lto-type-mismatch]
   62 | s_annot_to_aa1a(int n1, struct annot_str *annot_p, unsigned char *ann_arr);
      | ^
compacc2e.c:2313:1: note: type mismatch in parameter 1
 2313 | s_annot_to_aa1a(long offset, int n1, struct annot_str *annot_p, unsigned char *ann_arr, char *tmp_line) {
      | ^
compacc2e.c:2313:1: note: type ‘long int’ should match type ‘int’
compacc2e.c:2313:1: note: ‘s_annot_to_aa1a’ was previously declared here
compacc2e.c:2313:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
comp_lib9.c:250:5: error: type of ‘last_calc’ does not match original declaration [-Werror=lto-type-mismatch]
  250 | int last_calc( unsigned char **aa0, unsigned char *aa1, int maxn,
      |     ^
initfa.c:2036:1: note: type mismatch in parameter 6
 2036 | last_calc(
      | ^
initfa.c:2036:1: note: ‘last_calc’ was previously declared here
mshowbest.c:84:1: error: type of ‘get_annot’ does not match original declaration [-Werror=lto-type-mismatch]
   84 | get_annot(char *sname, struct mngmsg *m_msp, char *bline, int n1, struct annot_str **annot_p,
      | ^
compacc2e.c:2202:1: note: type mismatch in parameter 4
 2202 | get_annot(char *sname, struct mngmsg *m_msp, char *bline, long offset, int n1, struct annot_str **annot_p,
      | ^
compacc2e.c:2202:1: note: type ‘long int’ should match type ‘int’
compacc2e.c:2202:1: note: ‘get_annot’ was previously declared here
compacc2e.c:2202:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
comp_lib9.c:287:1: error: type of ‘showalign’ does not match original declaration [-Werror=lto-type-mismatch]
  287 | showalign (FILE *fp, unsigned char **aa0, unsigned char *aa1, int maxn,
      | ^
mshowalign2.c:134:6: note: ‘showalign’ was previously declared here
  134 | void showalign (FILE *fp, unsigned char **aa0, unsigned char *aa1save, int maxn,
      |      ^
mshowalign2.c:134:6: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [../make/Makefile.pcom_t:66: glsearch36] Error 1
```

... times a bunch of times, as a bunch of targets link with this exact issue.

Originally reported downstream: https://bugs.gentoo.org/862267

(That ticket talks about 36.3.8h, but I reproduced it against both 36.3.8i and a fresh git clone.)

Full build log: [build.log](https://github.com/user-attachments/files/16705285/build.log)

**Comment by wrpearson** [comment]
Looks like something that is easy to fix.

Hopefully in the next few days.

Bill Pearson

On Aug 21, 2024, at 10:11 PM, Eli Schwartz ***@***.***> wrote:

﻿

I tried to build with the following {C,CXX,FC,LD}FLAGS to optimize the build: -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing

Link-Time Optimization is a massively global compiler optimization pass which is pretty handy for producing faster executables. It also has the interesting property that because the compiler does whole-program analysis using bytecode, it can save type information and perform error checks that it normally doesn’t have enough insight for. In particular, checking for ODR issues and checking function type signature mismatches.

Note that all the -Werror=* flags are used to help detect cases where the compiler tries to optimize by assuming UB cannot exist in the source code -- if it does exist, ordinarily the code would be miscompiled, and this says to make the miscompilation a fatal error.

I got this error:

make: Entering directory '/var/tmp/portage/sci-biology/fasta-36.3.8i/work/fasta36-36.3.8i_14-Nov-2020/src'
x86_64-pc-linux-gnu-gcc -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -msse2 -ffast-math -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0 -o ../bin/glsearch36 comp_mthr9.o       work_thr2.o  pthr_subs2.o compacc2_t.o   showbest.o build_ares.o re_getlib.o mshowalign2_t.o htime.o apam.o doinit.o init_lnw_sse.o droplnw_sse.o glocal_sse2.o gwm_align.o calcons_sw.o scale_sn.o karlin.o  lgetlib.o lgetaa_m.o c_dispn.o ncbl2_mlib.o lib_sel.o url_subs.o mrandom.o pssm_asn_subs.o -lm   -lpthread
compacc2e.c:959:1: error: type of ‘re_openlib’ does not match original declaration [-Werror=lto-type-mismatch]
  959 | re_openlib(struct lmf_str *, int outtty);
      | ^
nmgetlib.c:514:3: note: type mismatch in parameter 2
  514 |   re_openlib(struct lmf_str *om_fptr, struct lib_struct *lib_p, int outtty)
      |   ^
nmgetlib.c:514:3: note: ‘re_openlib’ was previously declared here
nmgetlib.c:514:3: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
mshowbest.c:62:1: error: type of ‘s_annot_to_aa1a’ does not match original declaration [-Werror=lto-type-mismatch]
   62 | s_annot_to_aa1a(int n1, struct annot_str *annot_p, unsigned char *ann_arr);
      | ^
compacc2e.c:2313:1: note: type mismatch in parameter 1
 2313 | s_annot_to_aa1a(long offset, int n1, struct annot_str *annot_p, unsigned char *ann_arr, char *tmp_line) {
      | ^
compacc2e.c:2313:1: note: type ‘long int’ should match type ‘int’
compacc2e.c:2313:1: note: ‘s_annot_to_aa1a’ was previously declared here
compacc2e.c:2313:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
comp_lib9.c:250:5: error: type of ‘last_calc’ does not match original declaration [-Werror=lto-type-mismatch]
  250 | int last_calc( unsigned char **aa0, unsigned char *aa1, int maxn,
      |     ^
initfa.c:2036:1: note: type mismatch in parameter 6
 2036 | last_calc(
      | ^
initfa.c:2036:1: note: ‘last_calc’ was previously declared here
mshowbest.c:84:1: error: type of ‘get_annot’ does not match original declaration [-Werror=lto-type-mismatch]
   84 | get_annot(char *sname, struct mngmsg *m_msp, char *bline, int n1, struct annot_str **annot_p,
      | ^
compacc2e.c:2202:1: note: type mismatch in parameter 4
 2202 | get_annot(char *sname, struct mngmsg *m_msp, char *bline, long offset, int n1, struct annot_str **annot_p,
      | ^
compacc2e.c:2202:1: note: type ‘long int’ should match type ‘int’
compacc2e.c:2202:1: note: ‘get_annot’ was previously declared here
compacc2e.c:2202:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
comp_lib9.c:287:1: error: type of ‘showalign’ does not match original declaration [-Werror=lto-type-mismatch]
  287 | showalign (FILE *fp, unsigned char **aa0, unsigned char *aa1, int maxn,
      | ^
mshowalign2.c:134:6: note: ‘showalign’ was previously declared here
  134 | void showalign (FILE *fp, unsigned char **aa0, unsigned char *aa1save, int maxn,
      |      ^
mshowalign2.c:134:6: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [../make/Makefile.pcom_t:66: glsearch36] Error 1


... times a bunch of times, as a bunch of targets link with this exact issue.

Originally reported downstream: https://bugs.gentoo.org/862267

(That ticket talks about 36.3.8h, but I reproduced it against both 36.3.8i and a fresh git clone.)

Full build log: build.log<https://github.com/user-attachments/files/16705285/build.log>

**Comment by wrpearson** [comment]
The latest version of the fasta36  package dated August, 2024, compiles correctly with this higher level of compiler diagnostics.  Two warnings are shown, both of which I believe are false-positives.
